const navbar = document.querySelector('nav');
navbar.setAttribute('class', 'navbar fixed-top navbar-expand-lg navbar-light bg-light');

// Ram logo
const aTagLogo = document.createElement('a');
aTagLogo.setAttribute('class', 'navbar-brand');
const ramLogo = document.createElement('img');
ramLogo.setAttribute('src', 'RAMlab-logo.png');
ramLogo.setAttribute('width', '89');
ramLogo.setAttribute('height', '50');
ramLogo.setAttribute('alt', 'RAM Lab Logo');
aTagLogo.appendChild(ramLogo);
navbar.appendChild(aTagLogo);

// Button
const navButton = document.createElement('button');
navButton.setAttribute('class', 'navbar-toggler');
navButton.setAttribute('type', 'button');
navButton.setAttribute('data-toggle', 'collapse');
navButton.setAttribute('data-target', '#navbarSupportedContent');
navButton.setAttribute('aria-controls', 'navbarSupportedContent');
navButton.setAttribute('aria-expanded', 'false');
navButton.setAttribute('aria-label', 'Toggle navigation');
const navButtonSpan = document.createElement('span');
navButtonSpan.setAttribute('class', 'navbar-toggler-icon');
navButton.appendChild(navButtonSpan);
navbar.appendChild(navButton);

// Navbar Content
const contentDiv = document.createElement('div');
contentDiv.setAttribute('class', 'collapse navbar-collapse');
contentDiv.setAttribute('id', 'navbarSupportedContent');
navbar.appendChild(contentDiv);

const contentDivUl = document.createElement('ul');
contentDivUl.setAttribute('class', 'navbar-nav mx-auto');
contentDiv.appendChild(contentDivUl);

const li1 = document.createElement('li');
li1.setAttribute('class', 'nav-item');
contentDivUl.appendChild(li1);
const a1 = document.createElement('a');
a1.setAttribute('class', 'nav-link');
a1.setAttribute('href', 'index.html');
a1.textContent = 'Home';
li1.appendChild(a1);

const li2 = document.createElement('li');
li2.setAttribute('class', 'nav-item dropdown');
contentDivUl.appendChild(li2);
const a2 = document.createElement('a');
a2.setAttribute('class', 'nav-link dropdown-toggle');
a2.setAttribute('href', 'about.html');
a2.setAttribute('id', 'navbarDropdown');
a2.setAttribute('role', 'button');
a2.setAttribute('data-toggle', 'dropdown');
a2.setAttribute('aria-haspopup', 'true');
a2.setAttribute('aria-expanded', 'false');
a2.textContent = 'People';
li2.appendChild(a2);
const div2dropdown = document.createElement('div');
div2dropdown.setAttribute('class', 'dropdown-menu');
div2dropdown.setAttribute('aria-labelledby', 'navbarDropdown');
li2.appendChild(div2dropdown);
const div2a1 = document.createElement('a');
div2a1.setAttribute('class', 'dropdown-item');
div2a1.setAttribute('href', 'about.html');
div2a1.textContent = 'Faculty';
div2dropdown.appendChild(div2a1);
const div2a2 = document.createElement('a');
div2a2.setAttribute('class', 'dropdown-item');
div2a2.setAttribute('href', 'lab-members.html');
div2a2.textContent = 'Current members';
div2dropdown.appendChild(div2a2);
const div2a3 = document.createElement('a');
div2a3.setAttribute('class', 'dropdown-item');
div2a3.setAttribute('href', 'alumni-graduates.html');
div2a3.textContent = 'Graduate alumni';
div2dropdown.appendChild(div2a3);
const div2a4 = document.createElement('a');
div2a4.setAttribute('class', 'dropdown-item');
div2a4.setAttribute('href', 'alumni-undergrads.html');
div2a4.textContent = 'Undergraduate/High school alumni';
div2dropdown.appendChild(div2a4);
const div2a5 = document.createElement('a');
div2a5.setAttribute('class', 'dropdown-item');
div2a5.setAttribute('href', 'awards.html');
div2a5.textContent = 'Student Awards';
div2dropdown.appendChild(div2a5);

const li3 = document.createElement('li');
li3.setAttribute('class', 'nav-item dropdown');
contentDivUl.appendChild(li3);
const a3 = document.createElement('a');
a3.setAttribute('class', 'nav-link dropdown-toggle');
a3.setAttribute('href', 'research.html');
a3.setAttribute('id', 'navbarDropdownPub');
a3.setAttribute('role', 'button');
a3.setAttribute('data-toggle', 'dropdown');
a3.setAttribute('aria-haspopup', 'true');
a3.setAttribute('aria-expanded', 'false');
a3.textContent = 'Publications';
li3.appendChild(a3);
const div3dropdown = document.createElement('div');
div3dropdown.setAttribute('class', 'dropdown-menu');
div3dropdown.setAttribute('aria-labelledby', 'navbarDropdown');
li3.appendChild(div3dropdown);
for(let i = 2025; i >= 2014; i--) {
	let year = document.createElement('a');
	year.setAttribute('class', 'dropdown-item');
	year.setAttribute('href', `research.html#${i}`);
	year.textContent = `${i}`;
	div3dropdown.appendChild(year);
}
const year2008to2013 = document.createElement('a');
year2008to2013.setAttribute('class', 'dropdown-item');
year2008to2013.setAttribute('href', 'research.html#20082013');
year2008to2013.textContent = '2008-2013';
div3dropdown.appendChild(year2008to2013);
const theses = document.createElement('a');
theses.setAttribute('class', 'dropdown-item');
theses.setAttribute('href', 'research.html#theses');
theses.textContent = 'Theses';
div3dropdown.appendChild(theses);

const li4 = document.createElement('li');
li4.setAttribute('class', 'nav-item');
contentDivUl.appendChild(li4);
const a4 = document.createElement('a');
a4.setAttribute('class', 'nav-link');
a4.setAttribute('href', 'funding.html');
a4.textContent = 'Funding';
li4.appendChild(a4);

const li5 = document.createElement('li');
li5.setAttribute('class', 'nav-item dropdown');
contentDivUl.appendChild(li5);
const a5 = document.createElement('a');
a5.setAttribute('class', 'nav-link dropdown-toggle');
a5.setAttribute('href', 'teaching.html');
a5.setAttribute('id', 'navbarDropdownTeach');
a5.setAttribute('role', 'button');
a5.setAttribute('data-toggle', 'dropdown');
a5.setAttribute('aria-haspopup', 'true');
a5.setAttribute('aria-expanded', 'false');
a5.textContent = 'Teaching';
li5.appendChild(a5);
const div5dropdown = document.createElement('div');
div5dropdown.setAttribute('class', 'dropdown-menu');
div5dropdown.setAttribute('aria-labelledby', 'navbarDropdown');
li5.appendChild(div5dropdown);
const div5a1 = document.createElement('a');
div5a1.setAttribute('class', 'dropdown-item');
div5a1.setAttribute('href', 'courses.html');
div5a1.textContent = 'Courses';
div5dropdown.appendChild(div5a1);
const div5a2 = document.createElement('a');
div5a2.setAttribute('class', 'dropdown-item');
div5a2.setAttribute('href', 'teaching.html#tutorials');
div5a2.textContent = 'Tutorials';
div5dropdown.appendChild(div5a2);
const div5a3 = document.createElement('a');
div5a3.setAttribute('class', 'dropdown-item');
div5a3.setAttribute('href', 'teaching.html#outreach');
div5a3.textContent = 'Outreach';
div5dropdown.appendChild(div5a3);

const li6 = document.createElement('li');
li6.setAttribute('class', 'nav-item dropdown');
contentDivUl.appendChild(li6);
const a6 = document.createElement('a');
a6.setAttribute('class', 'nav-link dropdown-toggle');
a6.setAttribute('href', 'multimedia.html');
a6.setAttribute('id', 'navbarDropdownMedia');
a6.setAttribute('role', 'button');
a6.setAttribute('data-toggle', 'dropdown');
a6.setAttribute('aria-haspopup', 'true');
a6.setAttribute('aria-expanded', 'false');
a6.textContent = 'Multimedia';
li6.appendChild(a6);
const div6dropdown = document.createElement('div');
div6dropdown.setAttribute('class', 'dropdown-menu');
div6dropdown.setAttribute('aria-labelledby', 'navbarDropdown');
li6.appendChild(div6dropdown);
const div6a1 = document.createElement('a');
div6a1.setAttribute('class', 'dropdown-item');
div6a1.setAttribute('href', 'videos.html');
div6a1.textContent = 'Videos';
div6dropdown.appendChild(div6a1);
const div6a2 = document.createElement('a');
div6a2.setAttribute('class', 'dropdown-item');
div6a2.setAttribute('href', 'robots.html');
div6a2.textContent = 'Robots';
div6dropdown.appendChild(div6a2);
const div6a3 = document.createElement('a');
div6a3.setAttribute('class', 'dropdown-item');
div6a3.setAttribute('href', 'articles.html');
div6a3.textContent = 'Articles';
div6dropdown.appendChild(div6a3);

const li7 = document.createElement('li');
li7.setAttribute('class', 'nav-item');
contentDivUl.appendChild(li7);
const a7 = document.createElement('a');
a7.setAttribute('class', 'nav-link');
a7.setAttribute('href', 'contact.html');
a7.textContent = 'Contact';
li7.appendChild(a7);